import os
import base64

# Base64 strings for simple 48x48 colored squares
# Grey
b64_grey = "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAKElEQVRo3u3QMQEAAAwCoNk/tHM4hAAAAAAAAAAAAAAAAMDaAABmXz01AAGs943GAAAAAElFTkSuQmCC"
# Green
b64_green = "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAKElEQVRo3u3QMQEAAAwCoP17un44hAAAAAAAAAAAAAAAAMDaAABmXz0tQAHAQJ5qAAAAAElFTkSuQmCC"
# Red
b64_red = "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAKElEQVRo3u3QMQEAAAwCoP6vXg84hAAAAAAAAAAAAAAAAMDaAABmXz3+QAHUfH2RAAAAAElFTkSuQmCC"

# 16x16 Grey
b64_16 = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAIElEQVQ4y2P8//8/AyUYw2jYqGFEgoGFhWUYDcMw1AAAhwUGAN3+aVQAAAAASUVORK5CYII="
# 128x128 Grey
b64_128 = "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAARUlEQVR42u3BAQ0AAADCoPdPbQ43IQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC/AdsAAAE12wXJAAAAAElFTkSuQmCC"

icons = {
  'icon16.png': b64_16,
  'icon48.png': b64_grey,
  'icon128.png': b64_128,
  'icon_safe.png': b64_green,
  'icon_phishing.png': b64_red
}

os.makedirs('extension/icons', exist_ok=True)
for path, data in icons.items():
    with open(f'extension/icons/{path}', 'wb') as f:
        f.write(base64.b64decode(data))

print('Icons created successfully.')
